[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
gif = "0.13.1"
image = "0.25.6"
num = "0.4.3"
clap = { version = "4.4", features = ["derive"] }
indicatif = "0.17.11"
